### PR TITLE
PEP8 compliant & redundant code removed

### PR DESCRIPTION
**Pull request by RaghavaDhanya**
Add hackoctoberfest label and merge!

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
Not completely PEP8 compliant yet.  
And what was the redundant code?

**Comment by RaghavaDhanya** [comment]
The redundant code was Boolean comparison with "=="
Can you explain why line no 116 is used in your code? it only runs once right?

**Comment by SubhrajyotiSen** [comment]
line 116 is redundant as of now. It was added as a part of an initial test and later I forgot to remove it.

**Comment by RaghavaDhanya** [comment]
it should've been added in init method. I'm not gonna touch that.

**Comment by RaghavaDhanya** [comment]
Max line length is now PEP8 compliant.

**Comment by RaghavaDhanya** [comment]
don't forget to add label though

**Comment by RaghavaDhanya** [comment]
Removed few semicolons here and there!

**Pull request merged**
